# Generated by Django 3.2.7 on 2022-09-12 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': '日記'},
        ),
    ]
